version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.26.0
    working_directory: ~/project

jobs:
  lint:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Install golangci-lint
          command: |
            go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - run:
          name: Run golangci-lint
          command: |
            $(go env GOPATH)/bin/golangci-lint run ./...
      - run:
          name: Run Unit Tests
          command: |
            go test -v ./...

  vulncheck:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Install govulncheck
          command: |
            go install golang.org/x/vuln/cmd/govulncheck@latest
      - run:
          name: Run govulncheck
          command: |
            $(go env GOPATH)/bin/govulncheck ./...

  build:
    executor: go-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Build Go Binary locally
          command: |
            cd api/services/authx
            go build -v -ldflags "-X main.build=${CIRCLE_SHA1}"
      - run:
          name: Build Docker Image
          command: |
            docker build \
              --build-arg BUILD_REF="${CIRCLE_SHA1}" \
              --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
              -t authx:${CIRCLE_SHA1} .

workflows:
  version: 2
  ci-cd-pipeline:
    jobs:
      - lint
      - vulncheck:
          requires:
            - lint
      - build:
          requires:
            - vulncheck
